# Assignment 04

## Import Libraries

In [23]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

## Read, analyse and preprocess data 

In [24]:
address=r'D:\Machine Learning\Assignment\Assignment 4\titanic (1).csv'
df = pd.read_csv(address)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [26]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [27]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [28]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [29]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:
X = df[['Pclass','SibSp','Parch','Fare']]
y = df.Survived

In [31]:
y.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [32]:
X.head()

Pclass  SibSp  Parch     Fare
0       3      1      0   7.2500
1       1      1      0  71.2833
2       3      0      0   7.9250
3       1      1      0  53.1000
4       3      0      0   8.0500

In [33]:
# Scaling the data
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()
X = Scaler.fit_transform(X)

In [34]:
pd.DataFrame(X).describe()

0             1             2             3
count  8.910000e+02  8.910000e+02  8.910000e+02  8.910000e+02
mean  -2.031048e-16  3.456519e-16  6.716164e-17 -4.373606e-17
std    1.000562e+00  1.000562e+00  1.000562e+00  1.000562e+00
min   -1.566107e+00 -4.745452e-01 -4.736736e-01 -6.484217e-01
25%   -3.693648e-01 -4.745452e-01 -4.736736e-01 -4.891482e-01
50%    8.273772e-01 -4.745452e-01 -4.736736e-01 -3.573909e-01
75%    8.273772e-01  4.327934e-01 -4.736736e-01 -2.424635e-02
max    8.273772e-01  6.784163e+00  6.974147e+00  9.667167e+00

## Split Dataset for Training and Testing 

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# 1.Logistic Regression

In [52]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6591928251121076


In [53]:
cm = confusion_matrix(y_test, y_pred)  
print(cm)

[[109  25]
 [ 51  38]]


### K-Fold Cross Validation 

In [56]:
from sklearn.model_selection import cross_val_score,KFold
model = LogisticRegression()
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores are {}".format(score))

Cross Validation Scores are [0.62569832 0.66853933 0.66853933 0.69662921 0.75280899]


In [57]:
print("Average Cross Validation score :{}".format(score.mean()))

Average Cross Validation score :0.6824430355909861


# 2.KNN

In [48]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5)
#Fitting the model
neigh.fit(X_train,y_train) 
y_pred = neigh.predict(X_test)
# Checking accuracy
from sklearn.metrics import accuracy_score
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6636771300448431


In [43]:
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred)  
print(cm)

[[113  21]
 [ 59  30]]


### K-Fold Cross Validation 

In [58]:
model = KNeighborsClassifier(n_neighbors=5)
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores are {}".format(score))

Cross Validation Scores are [0.5698324  0.61797753 0.70786517 0.7247191  0.70224719]


In [59]:
print("Average Cross Validation score :{}".format(score.mean()))

Average Cross Validation score :0.6645282781997364


# 3.SVM

In [47]:
from sklearn.svm import SVC
model1 = SVC(kernel='linear', C=1, gamma='auto')
model1.fit(X_train,y_train)            
y_pred = model1.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6412556053811659


In [44]:
confusion_matrix(y_test, y_pred)

array([[113,  21],
       [ 59,  30]], dtype=int64)

### K-Fold Cross Validation 

In [60]:
model = SVC(kernel='linear', C=1, gamma='auto')
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores are {}".format(score))

Cross Validation Scores are [0.62011173 0.61235955 0.66292135 0.7247191  0.69101124]


In [61]:
print("Average Cross Validation score :{}".format(score.mean()))

Average Cross Validation score :0.6622245935597263


# 4.DecisionTree

In [45]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6502242152466368


In [46]:
confusion_matrix(y_test, y_pred)

array([[106,  28],
       [ 50,  39]], dtype=int64)

### K-Fold Cross Validation 

In [62]:
model = DecisionTreeClassifier()
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores are {}".format(score))

Cross Validation Scores are [0.67039106 0.62921348 0.69662921 0.69662921 0.73595506]


In [63]:
print("Average Cross Validation score :{}".format(score.mean()))

Average Cross Validation score :0.6857636055489297


# 5.RandomForest

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=42, n_estimators=100)
rf_clf.fit(X_train, y_train)
y_pred = rf_clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6502242152466368


In [51]:
confusion_matrix(y_test, y_pred)

array([[105,  29],
       [ 49,  40]], dtype=int64)

### K-Fold Cross Validation 

In [64]:
model = RandomForestClassifier(random_state=42, n_estimators=100)
kf=KFold(n_splits=5)
score=cross_val_score(model,X,y,cv=kf)
print("Cross Validation Scores are {}".format(score))

Cross Validation Scores are [0.63687151 0.64044944 0.68539326 0.73595506 0.73595506]


In [65]:
print("Average Cross Validation score :{}".format(score.mean()))

Average Cross Validation score :0.6869248634737304


#  Grid search using SVM

In [66]:
from sklearn.model_selection import GridSearchCV

In [67]:
parameters ={'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']}

In [69]:
from sklearn import ensemble
grid_search = GridSearchCV(SVC(), 
    parameters, 
    cv=5,
    scoring='accuracy',n_jobs=-1)

In [70]:
grid_result= grid_search.fit(X_train, y_train)

In [71]:
print('Best Params: ', grid_result.best_params_)
print('Best Score: ', grid_result.best_score_)


Best Params:  {'C': 1, 'gamma': 1, 'kernel': 'rbf'}
Best Score:  0.7380540904500056
